import { Theme } from "theme-ui";

export const theme: Theme = {
  colors: {
    text: "#000",
    background: "#000",
    primary: "#fff",
    active: "#fff",
    inactive: "#bbb",
    lcarsRed1: "#ff5555",
    lcarsRed2: "#dd4444",
    lcarsRed3: "#ff2200",
    lcarsOrange1: "#ff9966",
    lcarsOrange2: "#ff8866",
    lcarsOrange3: "#ff7700",
    lcarsPurple1: "#ddbbff",
    lcarsPurple2: "#cc88ff",
    lcarsPurple3: "#9944ff",
    lcarsBlue1: "#aaaaff",
    lcarsBlue2: "#7788ff",
    lcarsBlue3: "#4455ff",
    lcarsYellow1: "#ffcc66",
    lcarsYellow2: "#ffcc33",
    lcarsYellow3: "#ffaa00",
    lcarsGreen1: "#33cc99",
    lcarsGreen2: "#99dd66",
    lcarsGreen3: "#00bb00",
    lcarsInactive: "#666688",
    lcarsWhite: "#f5f6fa",
    lcarsColourBlack: "#090909",
    lcarsBackground: "#090909",
  },
  fonts: {
    body: "Antonio, sans-serif",
    heading: "Antonio, sans-serif",
  },
  images: {
    avatar: {
      width: 200,
      height: "auto",
      backgroundColor: "muted",
      borderRadius: "100%",
      border: "3px solid",
      borderColor: "primary",
      marginX: "auto",
      display: "block",
    },
  },
  buttons: {
    primary: {
      fontFamily: "Antonio, sans-serif",
      fontSize: 3,
      minWidth: "200px",
      color: "background",
      paddingY: 3,
      bg: "primary",
      "&:hover": {
        cursor: "pointer",
        bg: "secondary",
      },
    },
    secondary: {
      color: "background",
      bg: "secondary",
    },
  },
  fontWeights: {
    body: 400,
    heading: 700,
    bold: 700,
  },
  lineHeights: {
    body: 1.5,
    heading: 1.125,
  },
  text: {
    heading: {
      fontFamily: "Antonio, sans-serif",
      fontSize: 4,
    },
    NavLink: {
      fontFamily: "Antonio, sans-serif",
      fontSize: 3,
    },
  },
  links: {
    nav: {
      fontFamily: "Antonio, sans-serif",
      fontSize: 3,
      cursor: "pointer",
    },
  },
  space: [
    0,
    "5px",
    "10px",
    "16px",
    "10px",
    "24px",
    "36px",
    "50px",
    "100px",
    "185px",
    "215px",
  ],
  sizes: [
    0,
    "5px",
    "10px",
    "16px",
    "10px",
    "24px",
    "36px",
    "50px",
    "100px",
    "185px",
    "215px",
  ],
};
